import Footer from '@/components/layout/Footer';
import Navigation from '@/components/layout/Navigation';
import type { Metadata } from 'next';
import { Inter, Roboto } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({
	weight: ['400', '700'],
	subsets: ['latin'],
	variable: '--font-roboto',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} ${roboto.variable} antialiased`}>
				<Navigation />
				{children}
				<Footer />
			</body>
		</html>
	);
}
